# Generated by Django 3.1.2 on 2020-11-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='AutoModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30, verbose_name='Модель')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.autobrand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('brand', models.CharField(max_length=30, verbose_name='Марка')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('data', models.DateField(verbose_name='Предпочиемые дата записи')),
                ('time', models.TimeField(verbose_name='Предпочитаемое время записи')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Номер телефона')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Допонительная информация')),
            ],
            options={
                'verbose_name': 'Запись на ТО',
                'verbose_name_plural': 'Записи на ТО',
            },
        ),
        migrations.CreateModel(
            name='TestDriveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('data', models.DateField(verbose_name='Предпочиемые дата записи')),
                ('time', models.TimeField(verbose_name='Предпочитаемое время записи')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Номер телефона')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Допонительная информация')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.autobrand', verbose_name='Марка')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.automodels', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Запись на тест-драйв',
                'verbose_name_plural': 'Записи на тест-драйв',
            },
        ),
        migrations.CreateModel(
            name='AutoCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(blank=True, max_length=15, null=True, verbose_name='Двигатель(литров)')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='Мощность')),
                ('transmission', models.CharField(choices=[('автомат', 'автомат'), ('механика', 'механика')], default='механическая', max_length=15, verbose_name='Трансмиссия')),
                ('drive_wheel', models.CharField(choices=[('полный', 'полный'), ('передний', 'передний'), ('задний', 'задний')], default='передний', max_length=10, verbose_name='Привод')),
                ('body_type', models.CharField(choices=[('седан', 'седан'), ('хетчбек', 'хетчбек'), ('кроссовер', 'кроссовер')], default='седан', max_length=15, verbose_name='Тип кузова')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('steering_wheel', models.CharField(choices=[('левый', 'левый'), ('правый', 'правый')], default='левый', max_length=8, verbose_name='Руль')),
                ('engine_type', models.CharField(choices=[('бензин', 'бензин'), ('дизель', 'дизель')], default='бензин', max_length=20, verbose_name='Тип двигателя')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('discount', models.IntegerField(verbose_name='Скидочная цена')),
                ('main_photo', models.ImageField(upload_to='', verbose_name='Главное фото')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дополнительное фото 1')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дополнительное фото 2')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дополнительное фото 3')),
                ('description', models.TextField(default='Нет описания', verbose_name='Описание')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В "Избранных"')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mbrand', to='main_app.autobrand', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mmodel', to='main_app.automodels', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
    ]
