# Generated by Django 3.1.2 on 2020-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201121_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrivemodel',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Фото'),
        ),
    ]
